version: '3'

services:
  joomla:
    image: joomla:latest
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8028:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: Ayush
      JOOMLA_DB_PASSWORD: redhat
      JOOMLA_DB_NAME: mydb2
    volumes:
      - joomla_storage_new:/var/www/html

  joomladb:
    image: mysql:5.7
    volumes:
      - mysql_storage_new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: Ayush
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb2


volumes:
  joomla_storage_new:
  mysql_storage_new:

